# Generated by Django 5.1.6 on 2026-07-10 11:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomiciliationPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('durée', models.PositiveIntegerField(help_text='Durée en mois')),
                ('avantages', models.TextField(help_text='Liste des avantages, séparés par des retours à la ligne')),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(db_index=True, default=0, help_text='Ordre d’affichage')),
            ],
            options={
                'verbose_name': 'Formule de domiciliation',
                'verbose_name_plural': 'Formules de domiciliation',
                'ordering': ['ordre'],
                'indexes': [models.Index(fields=['slug'], name='domiciliati_slug_4a6dae_idx'), models.Index(fields=['actif'], name='domiciliati_actif_7a2160_idx')],
            },
        ),
        migrations.CreateModel(
            name='DomiciliationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_demande', models.CharField(db_index=True, max_length=60, unique=True)),
                ('statut', models.CharField(choices=[('Brouillon', 'Brouillon'), ('En attente', 'En attente'), ('Documents reçus', 'Documents reçus'), ('En vérification', 'En vérification'), ('Contrat généré', 'Contrat généré'), ('Signature en attente', 'Signature en attente'), ('Paiement en attente', 'Paiement en attente'), ('Active', 'Active'), ('Refusée', 'Refusée'), ('Expirée', 'Expirée'), ('Résiliée', 'Résiliée')], default='Brouillon', max_length=64)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('adresse_domiciliation', models.TextField()),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('derniere_modification', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(help_text='Entreprise concernée par la domiciliation', on_delete=django.db.models.deletion.CASCADE, related_name='domiciliation_requests', to='accounts.company')),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domiciliation_requests', to='domiciliation.domiciliationplan')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domiciliation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de domiciliation',
                'verbose_name_plural': 'Demandes de domiciliation',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DomiciliationRenewal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nouvelle_periode', models.PositiveIntegerField(help_text='Durée en mois')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('statut', models.CharField(db_index=True, default='En attente', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renouvellements', to='domiciliation.domiciliationrequest')),
            ],
            options={
                'verbose_name': 'Renouvellement de domiciliation',
                'verbose_name_plural': 'Renouvellements de domiciliation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DomiciliationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domiciliation_logs', to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='domiciliation.domiciliationrequest')),
            ],
            options={
                'verbose_name': 'Journal de domiciliation',
                'verbose_name_plural': 'Journaux de domiciliation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DomiciliationInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=80, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fichier_pdf', models.FileField(max_length=500, upload_to='domiciliation/invoices/%Y/%m/%d/')),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Payée', 'Payée'), ('Annulée', 'Annulée')], db_index=True, default='En attente', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='domiciliation.domiciliationrequest')),
            ],
            options={
                'verbose_name': 'Facture de domiciliation',
                'verbose_name_plural': 'Factures de domiciliation',
            },
        ),
        migrations.CreateModel(
            name='DomiciliationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[("Pièce d'identité", "Pièce d'identité"), ('RCCM', 'RCCM'), ('Statuts', 'Statuts'), ('Attestation', 'Attestation'), ('Justificatif', 'Justificatif'), ('Autre', 'Autre')], max_length=64)),
                ('fichier', models.FileField(max_length=500, upload_to='domiciliation/documents/%Y/%m/%d/')),
                ('validé', models.BooleanField(db_index=True, default=False)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='domiciliation.domiciliationrequest')),
            ],
            options={
                'verbose_name': 'Document de domiciliation',
                'verbose_name_plural': 'Documents de domiciliation',
            },
        ),
        migrations.CreateModel(
            name='DomiciliationContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=80, unique=True)),
                ('fichier_pdf', models.FileField(max_length=500, upload_to='domiciliation/contracts/%Y/%m/%d/')),
                ('signature_docuseal', models.CharField(blank=True, default='', help_text='ID Docuseal envelope', max_length=120)),
                ('signé', models.BooleanField(default=False)),
                ('date_signature', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='domiciliation.domiciliationrequest')),
            ],
            options={
                'verbose_name': 'Contrat de domiciliation',
                'verbose_name_plural': 'Contrats de domiciliation',
            },
        ),
        migrations.AddIndex(
            model_name='domiciliationrequest',
            index=models.Index(fields=['statut'], name='domiciliati_statut_5187a9_idx'),
        ),
        migrations.AddIndex(
            model_name='domiciliationrequest',
            index=models.Index(fields=['date_fin'], name='domiciliati_date_fi_25e48d_idx'),
        ),
        migrations.AddIndex(
            model_name='domiciliationrequest',
            index=models.Index(fields=['entreprise'], name='domiciliati_entrepr_314fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='domiciliationrequest',
            index=models.Index(fields=['utilisateur'], name='domiciliati_utilisa_65e7c4_idx'),
        ),
        migrations.AddIndex(
            model_name='domiciliationrenewal',
            index=models.Index(fields=['demande'], name='domiciliati_demande_4f6be9_idx'),
        ),
        migrations.AddIndex(
            model_name='domiciliationrenewal',
            index=models.Index(fields=['statut'], name='domiciliati_statut_442d55_idx'),
        ),
        migrations.AddIndex(
            model_name='domiciliationlog',
            index=models.Index(fields=['demande'], name='domiciliati_demande_9b22f7_idx'),
        ),
        migrations.AddIndex(
            model_name='domiciliationlog',
            index=models.Index(fields=['created_at'], name='domiciliati_created_9c31fa_idx'),
        ),
        migrations.AddIndex(
            model_name='domiciliationinvoice',
            index=models.Index(fields=['demande'], name='domiciliati_demande_a57a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='domiciliationinvoice',
            index=models.Index(fields=['statut'], name='domiciliati_statut_adb9b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='domiciliationinvoice',
            constraint=models.UniqueConstraint(fields=('demande',), name='uniq_invoice_per_request'),
        ),
        migrations.AddIndex(
            model_name='domiciliationdocument',
            index=models.Index(fields=['demande'], name='domiciliati_demande_bd52de_idx'),
        ),
        migrations.AddIndex(
            model_name='domiciliationdocument',
            index=models.Index(fields=['type'], name='domiciliati_type_6750b8_idx'),
        ),
        migrations.AddIndex(
            model_name='domiciliationdocument',
            index=models.Index(fields=['validé'], name='domiciliati_validé_3a5d08_idx'),
        ),
        migrations.AddConstraint(
            model_name='domiciliationdocument',
            constraint=models.UniqueConstraint(fields=('demande', 'type'), name='uniq_document_type_per_request'),
        ),
        migrations.AddIndex(
            model_name='domiciliationcontract',
            index=models.Index(fields=['demande'], name='domiciliati_demande_c620dd_idx'),
        ),
    ]
