# Generated by Django 6.0.6 on 2026-07-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domiciliation', '0004_alter_domiciliationcontract_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domiciliationrequest',
            name='type_demande',
            field=models.CharField(choices=[('EI', 'Entreprise Individuelle'), ('SARL', 'SARL'), ('SARLU', 'SARLU'), ('SAS', 'SAS'), ('SASU', 'SASU'), ('ONG', 'ONG'), ('STARTUP', 'Startup'), ('SCI', 'SCI'), ('ASSOCIATION', 'Association'), ('FONDATION', 'Fondation'), ('SCOOP', 'SCOOP')], default='EI', max_length=50),
        ),
    ]
