# Generated by Django 4.2.24 on 2026-07-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domiciliation', '0005_domiciliationrequest_type_demande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domiciliationcontract',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='domiciliationinvoice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='domiciliationplan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='domiciliationrequest',
            name='type_demande',
            field=models.CharField(choices=[('DOMICILIATION', 'Domiciliation simple'), ('EI', 'Entreprise Individuelle'), ('SARL', 'SARL'), ('SARLU', 'SARLU'), ('SAS', 'SAS'), ('SASU', 'SASU'), ('ONG', 'ONG'), ('STARTUP', 'Startup'), ('SCI', 'SCI'), ('ASSOCIATION', 'Association'), ('FONDATION', 'Fondation'), ('SCOOP', 'SCOOP')], default='DOMICILIATION', max_length=50),
        ),
    ]
