# Generated by Django 4.2.24 on 2026-07-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domiciliation', '0006_alter_domiciliationcontract_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domiciliationcontract',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='domiciliationinvoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='domiciliationplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
