# Generated by Django 4.2.24 on 2026-08-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domiciliation', '0007_alter_domiciliationcontract_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domiciliationrequest',
            name='statut',
            field=models.CharField(choices=[('Brouillon', 'Brouillon'), ('En attente', 'En attente'), ('Documents reçus', 'Documents reçus'), ('En vérification', 'En vérification'), ('Contrat généré', 'Contrat généré'), ('Contrat envoyé', 'Contrat envoyé'), ('Signature en attente', 'Signature en attente'), ('Paiement en attente', 'Paiement en attente'), ('Active', 'Active'), ('Refusée', 'Refusée'), ('Expirée', 'Expirée'), ('Résiliée', 'Résiliée')], default='Brouillon', max_length=64),
        ),
    ]
