# Generated by Django 4.2.24 on 2026-08-10 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_superuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domiciliation', '0008_alter_domiciliationrequest_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangementGerant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_nom', models.CharField(max_length=100, verbose_name="Nom de l'ancien gérant")),
                ('ancien_prenoms', models.CharField(max_length=150, verbose_name="Prénoms de l'ancien gérant")),
                ('ancien_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email de l'ancien gérant")),
                ('ancien_telephone', models.CharField(blank=True, max_length=30, verbose_name="Téléphone de l'ancien gérant")),
                ('nouveau_nom', models.CharField(max_length=100, verbose_name='Nom du nouveau gérant')),
                ('nouveau_prenoms', models.CharField(max_length=150, verbose_name='Prénoms du nouveau gérant')),
                ('nouveau_email', models.EmailField(max_length=254, verbose_name='Email du nouveau gérant')),
                ('nouveau_telephone', models.CharField(max_length=30, verbose_name='Téléphone du nouveau gérant')),
                ('nouveau_date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('nouveau_lieu_naissance', models.CharField(blank=True, max_length=150, verbose_name='Lieu de naissance')),
                ('nouveau_nationalite', models.CharField(blank=True, max_length=100, verbose_name='Nationalité')),
                ('nouveau_adresse', models.TextField(blank=True, verbose_name='Adresse du nouveau gérant')),
                ('date_prise_fonction', models.DateField(blank=True, null=True, verbose_name='Date de prise de fonction')),
                ('motif', models.TextField(verbose_name='Motif du changement')),
                ('piece_identite_ancien', models.FileField(blank=True, null=True, upload_to='gestion_entreprise/changement_gerant/', verbose_name="Pièce d'identité ancien gérant")),
                ('piece_identite_nouveau', models.FileField(blank=True, null=True, upload_to='gestion_entreprise/changement_gerant/', verbose_name="Pièce d'identité nouveau gérant")),
                ('proces_verbal', models.FileField(blank=True, null=True, upload_to='gestion_entreprise/changement_gerant/', verbose_name='Procès-verbal')),
                ('statuts', models.FileField(blank=True, null=True, upload_to='gestion_entreprise/changement_gerant/', verbose_name='Statuts')),
                ('rccm', models.FileField(blank=True, null=True, upload_to='gestion_entreprise/changement_gerant/', verbose_name='RCCM')),
                ('autres_documents', models.FileField(blank=True, null=True, upload_to='gestion_entreprise/changement_gerant/', verbose_name='Autres documents')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente'), ('EN_VERIFICATION', 'En vérification'), ('DOCUMENTS_MANQUANTS', 'Documents manquants'), ('EN_TRAITEMENT', 'En traitement'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=30, verbose_name='Statut')),
                ('commentaire_admin', models.TextField(blank=True, verbose_name='Commentaire administrateur')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant')),
                ('paiement_effectue', models.BooleanField(default=False, verbose_name='Paiement effectué')),
                ('reference_paiement', models.CharField(blank=True, max_length=150, verbose_name='Référence paiement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_terminaison', models.DateTimeField(blank=True, null=True, verbose_name='Date de terminaison')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_changement_gerant', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changements_gerant', to='accounts.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Changement de gérant',
                'verbose_name_plural': 'Changements de gérant',
                'ordering': ['-date_creation'],
            },
        ),
    ]
