# Generated by Django 4.2.24 on 2026-08-11 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_superuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domiciliation', '0010_modificationactivite_changementnomentreprise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepotMarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_marque', models.CharField(max_length=255, verbose_name='Nom de la marque')),
                ('type_marque', models.CharField(choices=[('VERBALE', 'Marque verbale'), ('FIGURATIVE', 'Marque figurative'), ('MIXTE', 'Marque mixte'), ('SONORE', 'Marque sonore'), ('AUTRE', 'Autre')], default='VERBALE', max_length=100, verbose_name='Type de marque')),
                ('description_marque', models.TextField(blank=True, verbose_name='Description de la marque')),
                ('slogan', models.CharField(blank=True, max_length=255, verbose_name='Slogan')),
                ('titulaire_nom', models.CharField(max_length=150, verbose_name='Nom du titulaire')),
                ('titulaire_prenoms', models.CharField(blank=True, max_length=200, verbose_name='Prénoms du titulaire')),
                ('titulaire_adresse', models.TextField(blank=True, verbose_name='Adresse du titulaire')),
                ('titulaire_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du titulaire')),
                ('titulaire_telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone du titulaire')),
                ('classes_nice', models.CharField(max_length=255, verbose_name='Classes de Nice')),
                ('produits_services', models.TextField(verbose_name='Produits et services concernés')),
                ('pays_protection', models.CharField(default="Côte d'Ivoire", max_length=255, verbose_name='Pays de protection')),
                ('marque_deja_utilisee', models.BooleanField(default=False, verbose_name='Marque déjà utilisée')),
                ('date_premiere_utilisation', models.DateField(blank=True, null=True, verbose_name='Date de première utilisation')),
                ('motif', models.TextField(blank=True, verbose_name='Informations complémentaires')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('logo_marque', models.ImageField(blank=True, null=True, upload_to='gestion_entreprise/depot_marque/logos/', verbose_name='Logo de la marque')),
                ('piece_identite', models.FileField(blank=True, null=True, upload_to='gestion_entreprise/depot_marque/', verbose_name="Pièce d'identité")),
                ('justificatif_entreprise', models.FileField(blank=True, null=True, upload_to='gestion_entreprise/depot_marque/', verbose_name="Justificatif de l'entreprise")),
                ('document_marque', models.FileField(blank=True, null=True, upload_to='gestion_entreprise/depot_marque/', verbose_name='Document de la marque')),
                ('autres_documents', models.FileField(blank=True, null=True, upload_to='gestion_entreprise/depot_marque/', verbose_name='Autres documents')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_VERIFICATION', 'En vérification'), ('DOCUMENTS_MANQUANTS', 'Documents manquants'), ('EN_TRAITEMENT', 'En traitement'), ('DEPOSE', 'Déposé'), ('ACCEPTE', 'Accepté'), ('REJETE', 'Rejeté'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=30, verbose_name='Statut')),
                ('commentaire_admin', models.TextField(blank=True, verbose_name='Commentaire administrateur')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant')),
                ('paiement_effectue', models.BooleanField(default=False)),
                ('reference_paiement', models.CharField(blank=True, max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_depot', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_depot_marque', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots_marque', to='accounts.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Dépôt de marque',
                'verbose_name_plural': 'Dépôts de marque',
                'ordering': ['-date_creation'],
            },
        ),
    ]
