# Generated by Django 4.2.24 on 2026-08-11 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_create_superuser'),
        ('domiciliation', '0011_depotmarque'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedactionContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('CDI', 'Contrat CDI'), ('CDD', 'Contrat CDD'), ('BAIL', 'Contrat de bail'), ('PRESTATION', 'Contrat de prestation de services'), ('TRAVAIL', 'Contrat de travail'), ('PARTENARIAT', 'Contrat de partenariat'), ('SOUS_TRAITANCE', 'Contrat de sous-traitance'), ('VENTE', 'Contrat de vente'), ('AUTRE', 'Autre contrat')], max_length=30, verbose_name='Type de contrat')),
                ('objet', models.CharField(max_length=255, verbose_name='Objet du contrat')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('partie_1_nom', models.CharField(max_length=255, verbose_name='Nom de la première partie')),
                ('partie_1_type', models.CharField(choices=[('PERSONNE', 'Personne physique'), ('ENTREPRISE', 'Entreprise'), ('ORGANISATION', 'Organisation')], default='PERSONNE', max_length=100)),
                ('partie_1_adresse', models.TextField(blank=True)),
                ('partie_1_telephone', models.CharField(blank=True, max_length=30)),
                ('partie_1_email', models.EmailField(blank=True, max_length=254)),
                ('partie_2_nom', models.CharField(max_length=255, verbose_name='Nom de la deuxième partie')),
                ('partie_2_type', models.CharField(choices=[('PERSONNE', 'Personne physique'), ('ENTREPRISE', 'Entreprise'), ('ORGANISATION', 'Organisation')], default='ENTREPRISE', max_length=100)),
                ('partie_2_adresse', models.TextField(blank=True)),
                ('partie_2_telephone', models.CharField(blank=True, max_length=30)),
                ('partie_2_email', models.EmailField(blank=True, max_length=254)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('duree', models.CharField(blank=True, max_length=100)),
                ('conditions_particulieres', models.TextField(blank=True)),
                ('clauses_souhaitees', models.TextField(blank=True)),
                ('documents_fournis', models.FileField(blank=True, null=True, upload_to='gestion_entreprise/contrats/documents/')),
                ('contrat_final', models.FileField(blank=True, null=True, upload_to='gestion_entreprise/contrats/final/')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente'), ('EN_REDACTION', 'En rédaction'), ('A_VALIDER', 'À valider'), ('VALIDE', 'Validé'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=30)),
                ('commentaire_admin', models.TextField(blank=True)),
                ('montant_prestation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paiement_effectue', models.BooleanField(default=False)),
                ('reference_paiement', models.CharField(blank=True, max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redactions_contrats', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redactions_contrats', to='accounts.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Rédaction de contrat',
                'verbose_name_plural': 'Rédactions de contrats',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='FermetureEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('CESSATION_ACTIVITE', "Cessation d'activité"), ('DISSOLUTION', 'Dissolution'), ('LIQUIDATION', 'Liquidation'), ('RETRAITE', 'Départ à la retraite'), ('DIFFICULTES', 'Difficultés financières'), ('AUTRE', 'Autre motif')], max_length=50, verbose_name='Motif de fermeture')),
                ('motif_detail', models.TextField(blank=True, verbose_name='Précisions sur le motif')),
                ('date_cessation', models.DateField(blank=True, null=True, verbose_name='Date prévue de cessation')),
                ('activite_arretee', models.BooleanField(default=False, verbose_name='Activité déjà arrêtée')),
                ('dettes_en_cours', models.BooleanField(default=False, verbose_name='Dettes en cours')),
                ('dettes_details', models.TextField(blank=True, verbose_name='Détails des dettes')),
                ('employes', models.BooleanField(default=False, verbose_name='Employés')),
                ('nombre_employes', models.PositiveIntegerField(blank=True, default=0, verbose_name="Nombre d'employés")),
                ('litiges_en_cours', models.BooleanField(default=False, verbose_name='Litiges en cours')),
                ('litiges_details', models.TextField(blank=True, verbose_name='Détails des litiges')),
                ('liquidateur_nom', models.CharField(blank=True, max_length=255, verbose_name='Nom du liquidateur')),
                ('liquidateur_telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone du liquidateur')),
                ('liquidateur_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du liquidateur')),
                ('liquidateur_adresse', models.TextField(blank=True, verbose_name='Adresse du liquidateur')),
                ('piece_identite', models.FileField(blank=True, null=True, upload_to='gestion_entreprise/fermeture/', verbose_name="Pièce d'identité")),
                ('document_entreprise', models.FileField(blank=True, null=True, upload_to='gestion_entreprise/fermeture/', verbose_name="Document de l'entreprise")),
                ('decision_fermeture', models.FileField(blank=True, null=True, upload_to='gestion_entreprise/fermeture/', verbose_name='Décision de fermeture')),
                ('autres_documents', models.FileField(blank=True, null=True, upload_to='gestion_entreprise/fermeture/', verbose_name='Autres documents')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_VERIFICATION', 'En vérification'), ('DOCUMENTS_MANQUANTS', 'Documents manquants'), ('EN_TRAITEMENT', 'En traitement'), ('TERMINE', 'Terminé'), ('REJETE', 'Rejeté'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=30, verbose_name='Statut')),
                ('commentaire_admin', models.TextField(blank=True, verbose_name='Commentaire administrateur')),
                ('montant_prestation', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant de la prestation')),
                ('paiement_effectue', models.BooleanField(default=False)),
                ('reference_paiement', models.CharField(blank=True, max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('date_terminaison', models.DateTimeField(blank=True, null=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_fermeture_entreprise', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_fermeture', to='accounts.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': "Fermeture d'entreprise",
                'verbose_name_plural': "Fermetures d'entreprises",
                'ordering': ['-date_creation'],
            },
        ),
    ]
