# Generated by Django 6.0.6 on 2026-07-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevisFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('rccm', models.CharField(blank=True, default='', max_length=100, verbose_name='Numéro RCCM / RC')),
                ('secteur', models.CharField(max_length=100, verbose_name="Secteur d'activité")),
                ('taille_entreprise', models.CharField(max_length=50, verbose_name="Taille de l'entreprise")),
                ('adresse', models.CharField(blank=True, default='', max_length=500, verbose_name="Adresse de l'entreprise")),
                ('civilite', models.CharField(blank=True, default='mr', max_length=10, verbose_name='Civilité')),
                ('fonction', models.CharField(max_length=200, verbose_name='Fonction / Poste')),
                ('nom_complet', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email professionnel')),
                ('telephone', models.CharField(max_length=50, verbose_name='Téléphone')),
                ('telephone_secondaire', models.CharField(blank=True, default='', max_length=50, verbose_name='Téléphone secondaire')),
                ('type_formation', models.CharField(blank=True, default='', max_length=255, verbose_name='Type de formation souhaitée')),
                ('domaines', models.TextField(blank=True, default='', verbose_name='Domaine(s) de formation')),
                ('nombre_participants', models.PositiveIntegerField(default=10, verbose_name='Nombre de participants')),
                ('budget', models.DecimalField(decimal_places=2, default=500000, max_digits=14, verbose_name='Budget estimé (FCFA)')),
                ('date_debut_souhaitee', models.DateField(blank=True, null=True, verbose_name='Date de début souhaitée')),
                ('duree_souhaitee', models.CharField(blank=True, default='', max_length=50, verbose_name='Durée souhaitée')),
                ('lieu_formation', models.CharField(blank=True, default='nos-locaux', max_length=100, verbose_name='Lieu de formation')),
                ('objectifs', models.TextField(verbose_name='Objectifs de la formation')),
                ('public_cible', models.TextField(blank=True, default='', verbose_name='Public cible / Profil des participants')),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='devis_formation/', verbose_name='Document joint')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('lu_le', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Demande de devis formation',
                'verbose_name_plural': 'Demandes de devis formation',
                'ordering': ['-created_at'],
            },
        ),
    ]
