# Generated by Django 6.0.6 on 2026-07-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_devisformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DevisFormation',
        ),
    ]
