# Generated by Django 4.2.24 on 2026-08-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contactmessage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(choices=[('MODELE', 'Modèles de documents'), ('GUIDE', 'Guides & procédures'), ('ADMINISTRATIF', 'Documents administratifs'), ('BUSINESS', 'Ressources business'), ('JURIDIQUE', 'Ressources juridiques'), ('FISCAL', 'Ressources fiscales'), ('AUTRE', 'Autres ressources')], max_length=30)),
                ('type_fichier', models.CharField(choices=[('PDF', 'PDF'), ('WORD', 'Word'), ('EXCEL', 'Excel'), ('AUTRE', 'Autre')], default='PDF', max_length=20)),
                ('fichier', models.FileField(upload_to='ressources/documents/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ressources/images/')),
                ('est_public', models.BooleanField(default=True)),
                ('est_featured', models.BooleanField(default=False)),
                ('nombre_telechargements', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['-date_creation'],
            },
        ),
    ]
