# Generated by Django 4.2.24 on 2026-08-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ressource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ressource',
            options={'ordering': ['categorie', 'ordre', 'date_creation'], 'verbose_name': 'Ressource', 'verbose_name_plural': 'Ressources'},
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='est_featured',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='nombre_telechargements',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='type_fichier',
        ),
        migrations.AddField(
            model_name='ressource',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ressource',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='categorie',
            field=models.CharField(choices=[('CREATION', "Création d'entreprise"), ('GESTION', "Gestion d'entreprise"), ('DOMICILIATION', 'Domiciliation'), ('JURIDIQUE', 'Juridique'), ('FISCALITE', 'Fiscalité'), ('BUSINESS', 'Business'), ('AUTRE', 'Autres')], max_length=30),
        ),
    ]
