# Generated by Django 5.1.6 on 2026-07-08 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icone', models.CharField(blank=True, default='', max_length=120)),
                ('image', models.ImageField(upload_to='coworking/categories/images/')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CoworkingSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('adresse', models.CharField(blank=True, default='', max_length=255)),
                ('ville', models.CharField(blank=True, default='', max_length=120)),
                ('pays', models.CharField(blank=True, default='', max_length=120)),
                ('telephone', models.CharField(blank=True, default='', max_length=60)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('image_principale', models.ImageField(upload_to='coworking/spaces/images/')),
                ('logo', models.ImageField(upload_to='coworking/spaces/logos/')),
                ('horaires', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif')], default='active', max_length=20)),
            ],
            options={
                'verbose_name': 'CoworkingSpace',
                'verbose_name_plural': 'CoworkingSpaces',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('description', models.TextField(blank=True, default='')),
                ('capacite', models.PositiveIntegerField()),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etage', models.CharField(blank=True, default='', max_length=50)),
                ('numero', models.CharField(blank=True, default='', max_length=50)),
                ('prix_heure', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_demi_journee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_journee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_semaine', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_mois', models.DecimalField(decimal_places=2, max_digits=12)),
                ('caution', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disponible', models.BooleanField(default=True)),
                ('vedette', models.BooleanField(default=False)),
                ('image_principale', models.ImageField(upload_to='coworking/workspaces/images/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workspaces', to='coworking.category')),
                ('espace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='coworking.coworkingspace')),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'unique_together': {('espace', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='WorkspaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='coworking/workspaces/gallery/')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='coworking.workspace')),
            ],
            options={
                'verbose_name': 'WorkspaceImage',
                'verbose_name_plural': 'WorkspaceImages',
            },
        ),
        migrations.CreateModel(
            name='WorkspacePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prix_heure', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prix_demi_journee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prix_journee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prix_semaine', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prix_mois', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('espace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='coworking.workspace')),
            ],
            options={
                'verbose_name': 'WorkspacePrice',
                'verbose_name_plural': 'WorkspacePrices',
            },
        ),
        migrations.CreateModel(
            name='FavoriteWorkspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_workspaces', to=settings.AUTH_USER_MODEL)),
                ('espace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='coworking.workspace')),
            ],
            options={
                'verbose_name': 'FavoriteWorkspace',
                'verbose_name_plural': 'FavoriteWorkspaces',
                'unique_together': {('utilisateur', 'espace')},
            },
        ),
        migrations.CreateModel(
            name='WorkspaceAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('espace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='coworking.workspace')),
            ],
            options={
                'verbose_name': 'WorkspaceAvailability',
                'verbose_name_plural': 'WorkspaceAvailabilities',
                'indexes': [models.Index(fields=['date'], name='coworking_w_date_9f592f_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_links', to='coworking.equipment')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_links', to='coworking.workspace')),
            ],
            options={
                'verbose_name': 'WorkspaceEquipment',
                'verbose_name_plural': 'WorkspaceEquipments',
                'unique_together': {('workspace', 'equipment')},
            },
        ),
        migrations.CreateModel(
            name='WorkspaceReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.PositiveSmallIntegerField(help_text='Note de 1 à 5')),
                ('commentaire', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('espace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='coworking.workspace')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coworking_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WorkspaceReview',
                'verbose_name_plural': 'WorkspaceReviews',
                'unique_together': {('utilisateur', 'espace')},
            },
        ),
    ]
