# Generated by Django 6.0.6 on 2026-07-23 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0005_seed_workspaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='coworking.category'),
        ),
    ]
