# Generated by Django 5.1.6 on 2026-07-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/articles/'),
        ),
    ]
