# Generated by Django 4.2.24 on 2026-07-31 12:33

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_create_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True)),
                ('description_courte', models.TextField(blank=True, default='')),
                ('description_complete', models.TextField(blank=True, default='')),
                ('objectifs', models.TextField(blank=True, default='')),
                ('programme', models.TextField(blank=True, default='')),
                ('prerequis', models.TextField(blank=True, default='')),
                ('duree', models.PositiveIntegerField(help_text='Durée en heures')),
                ('niveau', models.CharField(choices=[('BEGINNER', 'Débutant'), ('INTERMEDIATE', 'Intermédiaire'), ('ADVANCED', 'Avancé')], db_index=True, max_length=30)),
                ('prix', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('image', models.ImageField(blank=True, null=True, upload_to='formation/formations/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='formation/formations/videos/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='formation/formations/pdfs/')),
                ('video_url', models.URLField(blank=True, help_text='Lien YouTube ou Vimeo', null=True)),
                ('certificat', models.BooleanField(default=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
            },
        ),
        migrations.CreateModel(
            name='FormationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie de formation',
                'verbose_name_plural': 'Catégories de formations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialite', models.CharField(blank=True, default='', max_length=200)),
                ('biographie', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='formation/trainers/photos/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='formation/trainers/cv/')),
                ('annees_experience', models.PositiveIntegerField(default=0)),
                ('competences', models.TextField(blank=True, default='')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('disponible', models.CharField(choices=[('available', 'Disponible'), ('unavailable', 'Indisponible')], db_index=True, default='available', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formateur',
                'verbose_name_plural': 'Formateurs',
            },
        ),
        migrations.CreateModel(
            name='FormationSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salle_reference', models.CharField(blank=True, default='', help_text='Référence interne de salle (future intégration)', max_length=100)),
                ('date_debut', models.DateField(db_index=True)),
                ('date_fin', models.DateField(db_index=True)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('nombre_maximum', models.PositiveIntegerField(help_text='Nombre maximum de places')),
                ('statut', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('open', 'Ouverte'), ('closed', 'Fermée'), ('canceled', 'Annulée')], db_index=True, default='open', max_length=30)),
                ('places_restantes', models.IntegerField(db_index=True, default=0)),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='formation.trainer')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='formation.formation')),
            ],
            options={
                'verbose_name': 'Session de formation',
                'verbose_name_plural': 'Sessions de formation',
            },
        ),
        migrations.CreateModel(
            name='FormationReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.PositiveSmallIntegerField(help_text='Note de 1 à 5')),
                ('commentaire', models.TextField(blank=True, default='')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
            },
        ),
        migrations.CreateModel(
            name='FormationRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(db_index=True, max_length=64, unique=True)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('canceled', 'Annulée'), ('refused', 'Refusée')], db_index=True, default='pending', max_length=30)),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formation_registrations', to='accounts.company')),
                ('formation', models.ForeignKey(blank=True, help_text='Formation liée (utile quand session est null)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='formation.formation')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_registrations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='formation.formationsession')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
            },
        ),
        migrations.CreateModel(
            name='FormationQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='formation/quotes/pdfs/')),
                ('statut', models.CharField(choices=[('draft', 'Brouillon'), ('ready', 'Prêt'), ('sent', 'Envoyé'), ('canceled', 'Annulé')], db_index=True, default='draft', max_length=30)),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='formation.formationregistration')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
            },
        ),
        migrations.CreateModel(
            name='FormationPedagogicalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='formation/pedagogical_documents/')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedagogical_documents', to='formation.formation')),
            ],
            options={
                'verbose_name': 'Document pédagogique',
                'verbose_name_plural': 'Documents pédagogiques',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormationPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('méthode', models.CharField(choices=[('card', 'Carte'), ('bank', 'Virement'), ('cash', 'Espèces'), ('other', 'Autre')], db_index=True, default='card', max_length=30)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué'), ('canceled', 'Annulé')], db_index=True, default='pending', max_length=30)),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='formation.formationregistration')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='FormationContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrat_pdf', models.FileField(blank=True, null=True, upload_to='formation/contracts/pdfs/')),
                ('signature_docuseal', models.TextField(blank=True, default='')),
                ('signé', models.BooleanField(db_index=True, default=False)),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('signed', 'Signé'), ('canceled', 'Annulé')], db_index=True, default='pending', max_length=30)),
                ('devis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='formation.formationquote')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
            },
        ),
        migrations.CreateModel(
            name='FormationCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificat_pdf', models.FileField(blank=True, null=True, upload_to='formation/certificates/pdfs/')),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='formation.formationregistration')),
            ],
            options={
                'verbose_name': 'Attestation',
                'verbose_name_plural': 'Attestations',
            },
        ),
        migrations.CreateModel(
            name='FormationAccessCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text="Code d'accès unique généré ou saisi par le formateur", max_length=64, unique=True)),
                ('actif', models.BooleanField(db_index=True, default=True)),
                ('attribue_le', models.DateTimeField(blank=True, null=True)),
                ('expire_le', models.DateTimeField(blank=True, null=True)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_code', to='formation.formationregistration')),
            ],
            options={
                'verbose_name': "Code d'accès cours",
                'verbose_name_plural': "Codes d'accès cours",
            },
        ),
        migrations.AddField(
            model_name='formation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formations', to='formation.formationcategory'),
        ),
        migrations.CreateModel(
            name='DevisFormation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Entreprise')),
                ('rccm', models.CharField(blank=True, max_length=100, verbose_name='RCCM / RC')),
                ('secteur', models.CharField(max_length=200, verbose_name="Secteur d'activité")),
                ('taille', models.CharField(blank=True, max_length=100, verbose_name="Taille de l'entreprise")),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('civilite', models.CharField(max_length=20)),
                ('fonction', models.CharField(max_length=150)),
                ('nom', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=30)),
                ('telephone2', models.CharField(blank=True, max_length=30)),
                ('participants', models.PositiveIntegerField(default=1)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('duree', models.CharField(blank=True, max_length=100)),
                ('objectifs', models.TextField()),
                ('public_cible', models.TextField(blank=True)),
                ('numero_devis', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('montant_propose', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('programme', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('message_client', models.TextField(blank=True)),
                ('validite', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='devis_formation/documents/')),
                ('devis_pdf', models.FileField(blank=True, null=True, upload_to='devis_formation/pdf/')),
                ('statut', models.CharField(choices=[('Nouvelle', 'Nouvelle'), ('En étude', 'En étude'), ('Devis envoyé', 'Devis envoyé'), ('Acceptée', 'Acceptée'), ('Refusée', 'Refusée')], default='Nouvelle', max_length=30)),
                ('lu', models.BooleanField(default=False)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_acceptation', models.DateTimeField(blank=True, null=True)),
                ('date_refus', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_formations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de devis formation',
                'verbose_name_plural': 'Demandes de devis formation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='formationsession',
            index=models.Index(fields=['formation', 'statut'], name='formation_f_formati_46de18_idx'),
        ),
        migrations.AddIndex(
            model_name='formationsession',
            index=models.Index(fields=['date_debut', 'statut'], name='formation_f_date_de_81c7da_idx'),
        ),
        migrations.AddIndex(
            model_name='formationreview',
            index=models.Index(fields=['membre'], name='formation_f_membre__e0bcc8_idx'),
        ),
        migrations.AddConstraint(
            model_name='formationreview',
            constraint=models.CheckConstraint(check=models.Q(('note__gte', 1), ('note__lte', 5)), name='formation_review_note_range'),
        ),
        migrations.AddIndex(
            model_name='formationregistration',
            index=models.Index(fields=['session', 'statut'], name='formation_f_session_ed025b_idx'),
        ),
        migrations.AddIndex(
            model_name='formationregistration',
            index=models.Index(fields=['membre', 'statut'], name='formation_f_membre__32454b_idx'),
        ),
        migrations.AddConstraint(
            model_name='formationregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('session__isnull', False)), fields=('membre', 'session'), name='formation_registration_unique_member_session'),
        ),
        migrations.AddIndex(
            model_name='formationpedagogicaldocument',
            index=models.Index(fields=['formation'], name='formation_f_formati_d3a5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='formation',
            index=models.Index(fields=['slug'], name='formation_f_slug_e2107f_idx'),
        ),
        migrations.AddIndex(
            model_name='formation',
            index=models.Index(fields=['actif'], name='formation_f_actif_f3db2f_idx'),
        ),
        migrations.AddIndex(
            model_name='formation',
            index=models.Index(fields=['prix'], name='formation_f_prix_24a903_idx'),
        ),
        migrations.AddIndex(
            model_name='formation',
            index=models.Index(fields=['niveau'], name='formation_f_niveau_075b65_idx'),
        ),
    ]
