# Generated by Django 5.1.6 on 2026-07-16 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_alter_formation_id_alter_formationcategory_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationPedagogicalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='formation/pedagogical_documents/')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedagogical_documents', to='formation.formation')),
            ],
            options={
                'verbose_name': 'Document pédagogique',
                'verbose_name_plural': 'Documents pédagogiques',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['formation'], name='formation_f_formati_d3a5b0_idx')],
            },
        ),
    ]
