# Generated by Django 5.1.6 on 2026-07-22 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_superuser'),
        ('formation', '0006_alter_formation_id_alter_formationcategory_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='formationregistration',
            name='formation_registration_unique_member_session',
        ),
        migrations.AlterField(
            model_name='formationregistration',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='formation.formationsession'),
        ),
        migrations.AddConstraint(
            model_name='formationregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('session__isnull', False)), fields=('membre', 'session'), name='formation_registration_unique_member_session'),
        ),
    ]
