# Generated by Django 5.1.6 on 2026-07-23 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0007_make_session_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationregistration',
            name='formation',
            field=models.ForeignKey(blank=True, help_text='Formation liée (utile quand session est null)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='formation.formation'),
        ),
    ]
