# Generated by Django 6.0.6 on 2026-07-22 09:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0001_initial'),
        ('reservation', '0003_paymentmethod_alter_reservationinvoice_statut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentprovider',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Fournisseur de paiement', 'verbose_name_plural': 'Fournisseurs de paiement'},
        ),
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transaction de paiement', 'verbose_name_plural': 'Transactions de paiement'},
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='config_json',
            field=models.JSONField(blank=True, default=dict, help_text='Paramètres additionnels au format JSON', verbose_name='Configuration supplémentaire (JSON)'),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='endpoint_url',
            field=models.CharField(blank=True, default='', help_text="URL de l'API pour les appels en production", max_length=500, verbose_name="URL de l'endpoint"),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='sandbox_endpoint',
            field=models.CharField(blank=True, default='', help_text="URL de l'API pour les appels en mode test", max_length=500, verbose_name='URL sandbox'),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='sandbox_mode',
            field=models.BooleanField(default=True, help_text="Utiliser l'environnement de test au lieu de la production", verbose_name='Mode test (sandbox)'),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(default='XOF', max_length=10, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email du payeur'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name="Message d'erreur"),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Numéro de téléphone'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='provider_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Données du fournisseur'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Référence locale'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Clé API'),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='api_secret',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Secret API'),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='code',
            field=models.CharField(choices=[('cinetpay', 'CinetPay'), ('paypal', 'PayPal'), ('orange', 'Orange Money'), ('wave', 'Wave'), ('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('visa', 'Visa / Mastercard'), ('stripe', 'Stripe'), ('manual', 'Paiement manuel')], max_length=50, unique=True, verbose_name='Code fournisseur'),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='merchant_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Identifiant marchand'),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom du fournisseur'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='paiement.paymentprovider', verbose_name='Fournisseur de paiement'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='reservation.reservation', verbose_name='Réservation'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('success', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], db_index=True, default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='ID Transaction'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_id'], name='paiement_pa_transac_1e8295_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['reference'], name='paiement_pa_referen_09f0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='paiement_pa_status_9be4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['created_at'], name='paiement_pa_created_fb79b7_idx'),
        ),
    ]
