# Generated by Django 6.0.6 on 2026-07-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeConciergerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('civilite', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=150)),
                ('fonction', models.CharField(max_length=150)),
                ('entreprise', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=30)),
                ('secteur', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('participants', models.PositiveIntegerField(default=1)),
                ('date_debut', models.DateField()),
                ('duree', models.CharField(max_length=50)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('horaires', models.CharField(max_length=100)),
                ('commentaire', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('etude', 'En étude'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('terminee', 'Terminée')], default='nouvelle', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
