"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os
from pathlib import Path
from dotenv import load_dotenv


# Charger le fichier .env
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")



# ==================================================
# CINETPAY
# ==================================================

CINETPAY_API_KEY = os.getenv(
    "CINETPAY_API_KEY"
)

CINETPAY_SITE_ID = os.getenv(
    "CINETPAY_SITE_ID"
)

CINETPAY_ENDPOINT = os.getenv(
    "CINETPAY_ENDPOINT"
)



# ==================================================
# ORANGE MONEY
# ==================================================

ORANGE_CLIENT_ID = os.getenv(
    "ORANGE_CLIENT_ID"
)

ORANGE_CLIENT_SECRET = os.getenv(
    "ORANGE_CLIENT_SECRET"
)

ORANGE_MERCHANT_ID = os.getenv(
    "ORANGE_MERCHANT_ID"
)

ORANGE_ENDPOINT = os.getenv(
    "ORANGE_ENDPOINT"
)



# ==================================================
# MTN MOBILE MONEY
# ==================================================

MTN_API_KEY = os.getenv(
    "MTN_API_KEY"
)

MTN_SUBSCRIPTION_KEY = os.getenv(
    "MTN_SUBSCRIPTION_KEY"
)

MTN_USER_ID = os.getenv(
    "MTN_USER_ID"
)

MTN_API_SECRET = os.getenv(
    "MTN_API_SECRET"
)

MTN_ENDPOINT = os.getenv(
    "MTN_ENDPOINT"
)

MTN_TARGET_ENVIRONMENT = os.getenv(
    "MTN_TARGET_ENVIRONMENT",
    "sandbox"
)



# ==================================================
# MOOV MONEY
# ==================================================

MOOV_API_KEY = os.getenv(
    "MOOV_API_KEY"
)

MOOV_MERCHANT_ID = os.getenv(
    "MOOV_MERCHANT_ID"
)

MOOV_USERNAME = os.getenv(
    "MOOV_USERNAME"
)

MOOV_PASSWORD = os.getenv(
    "MOOV_PASSWORD"
)

MOOV_ENDPOINT = os.getenv(
    "MOOV_ENDPOINT"
)



# ==================================================
# WAVE MONEY
# ==================================================

WAVE_API_KEY = os.getenv(
    "WAVE_API_KEY"
)

WAVE_SECRET_KEY = os.getenv(
    "WAVE_SECRET_KEY"
)

WAVE_ENDPOINT = os.getenv(
    "WAVE_ENDPOINT"
)



# ==================================================
# STRIPE
# ==================================================

STRIPE_SECRET_KEY = os.getenv(
    "STRIPE_SECRET_KEY"
)

STRIPE_PUBLIC_KEY = os.getenv(
    "STRIPE_PUBLIC_KEY"
)

STRIPE_WEBHOOK_SECRET = os.getenv(
    "STRIPE_WEBHOOK_SECRET"
)



# ==================================================
# PAYPAL
# ==================================================

PAYPAL_CLIENT_ID = os.getenv(
    "PAYPAL_CLIENT_ID"
)

PAYPAL_SECRET_KEY = os.getenv(
    "PAYPAL_SECRET_KEY"
)

PAYPAL_MODE = os.getenv(
    "PAYPAL_MODE",
    "sandbox"
)

PAYPAL_ENDPOINT = os.getenv(
    "PAYPAL_ENDPOINT"
)



# ==================================================
# VISA / MASTER CARD
# ==================================================

VISA_API_KEY = os.getenv(
    "VISA_API_KEY"
)

VISA_MERCHANT_ID = os.getenv(
    "VISA_MERCHANT_ID"
)

VISA_ENDPOINT = os.getenv(
    "VISA_ENDPOINT"
)



# ==================================================
# EMAIL
# ==================================================

EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
)


EMAIL_HOST = os.getenv(
    "EMAIL_HOST"
)

EMAIL_PORT = int(
    os.getenv(
        "EMAIL_PORT",
        587
    )
)


EMAIL_USE_TLS = (
    os.getenv(
        "EMAIL_USE_TLS",
        "True"
    ) == "True"
)


EMAIL_HOST_USER = os.getenv(
    "EMAIL_HOST_USER"
)


EMAIL_HOST_PASSWORD = os.getenv(
    "EMAIL_HOST_PASSWORD"
)



# ==================================================
# URL PAIEMENT
# ==================================================

SITE_URL = os.getenv(
    "SITE_URL",
    "http://127.0.0.1:8000"
)


PAYMENT_SUCCESS_URL = os.getenv(
    "PAYMENT_SUCCESS_URL"
)


PAYMENT_CANCEL_URL = os.getenv(
    "PAYMENT_CANCEL_URL"
)


PAYMENT_NOTIFY_URL = os.getenv(
    "PAYMENT_NOTIFY_URL"
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v^p72(a913s)d*l0m7hxo#gb@md=ej29+c6vafhw1m@6x$(iv8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'accounts',
    'blog',
    'coworking',
    'core',
    'dashboard',
    'domiciliation',
    'formation',
    'notification',
    'paiement',
    'reservation',
    'reclamation',
    'chatbot',
    'conciergerie',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

# Django Allauth

ACCOUNT_LOGIN_METHODS = {"email"}

ACCOUNT_SIGNUP_FIELDS = [
    "email*",
    "password1*",
    "password2*",
]

ACCOUNT_USER_MODEL_USERNAME_FIELD = None

ACCOUNT_EMAIL_VERIFICATION = "optional"

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    #'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = "accounts.User"

LOGIN_URL = "accounts:login"

# Redirection par défaut (compte auth)
LOGIN_REDIRECT_URL = "accounts:dashboard"



LOGOUT_REDIRECT_URL = "core:home"


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.gmail.com"

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_HOST_USER = "amahesther15@gmail.com"

EMAIL_HOST_PASSWORD = "peoe botf aybc ulds"

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


SOCIALACCOUNT_LOGIN_ON_GET = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"