# Generated by Django 5.1.6 on 2026-07-13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('coworking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('type_reservation', models.CharField(choices=[('private_office', 'Bureau privé'), ('hot_desk', 'Hot desk'), ('meeting_room', 'Salle de réunion'), ('training_room', 'Salle de formation'), ('conference_room', 'Salle de conférence')], db_index=True, max_length=50)),
                ('date_debut', models.DateField(db_index=True)),
                ('date_fin', models.DateField(db_index=True)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('nombre_participants', models.PositiveIntegerField(default=1)),
                ('duree_minutes', models.PositiveIntegerField(default=0)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('remise', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('taxes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('confirmed', 'Confirmée'), ('in_progress', 'En cours'), ('finished', 'Terminée'), ('canceled', 'Annulée'), ('refused', 'Refusée'), ('expired', 'Expirée')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='accounts.company')),
                ('espace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='coworking.workspace')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='ReservationParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=30)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='reservation.reservation')),
            ],
            options={
                'verbose_name': 'ReservationParticipant',
                'verbose_name_plural': 'ReservationParticipants',
            },
        ),
        migrations.CreateModel(
            name='ReservationInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(db_index=True, max_length=64, unique=True)),
                ('pdf', models.FileField(upload_to='reservation/invoices/pdfs/')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('statut', models.CharField(choices=[('draft', 'Brouillon'), ('issued', 'Émise'), ('paid', 'Payée'), ('canceled', 'Annulée')], default='draft', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='reservation.reservation')),
            ],
            options={
                'verbose_name': 'ReservationInvoice',
                'verbose_name_plural': 'ReservationInvoices',
            },
        ),
        migrations.CreateModel(
            name='ReservationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Création'), ('updated', 'Modification'), ('validated', 'Validation'), ('payment', 'Paiement'), ('canceled', 'Annulation'), ('confirmed', 'Confirmation'), ('finished', 'Clôture'), ('exported', 'Export PDF')], db_index=True, max_length=30)),
                ('detail', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_logs', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reservation.reservation')),
            ],
            options={
                'verbose_name': 'ReservationLog',
                'verbose_name_plural': 'ReservationLogs',
            },
        ),
        migrations.CreateModel(
            name='ReservationReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('created', 'Réservation créée'), ('confirmed', 'Réservation confirmée'), ('modified', 'Réservation modifiée'), ('canceled', 'Réservation annulée'), ('before', 'Rappel avant la réservation'), ('finished', 'Réservation terminée')], db_index=True, max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('internal', 'Notification interne')], default='email', max_length=20)),
                ('date_envoi', models.DateTimeField(db_index=True)),
                ('envoye', models.BooleanField(default=False)),
                ('destination', models.CharField(blank=True, default='', max_length=255)),
                ('titre', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='reservation.reservation')),
            ],
            options={
                'verbose_name': 'ReservationReminder',
                'verbose_name_plural': 'ReservationReminders',
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['espace', 'date_debut', 'date_fin'], name='reservation_espace__8baeb9_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['utilisateur', 'statut'], name='reservation_utilisateur__statut_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['entreprise', 'statut'], name='reservation_entreprise__statut_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('reservation_number',), name='reservation_reservation_number_unique'),
        ),
        migrations.AddIndex(
            model_name='reservationparticipant',
            index=models.Index(fields=['reservation'], name='reservationparticipant_reservation_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationparticipant',
            index=models.Index(fields=['email'], name='reservationparticipant_email_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationlog',
            index=models.Index(fields=['reservation', 'date_creation'], name='reservationlog_reservation__date_creation_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationreminder',
            index=models.Index(fields=['reservation', 'date_envoi'], name='reservationreminder_reservation__date_envoi_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationreminder',
            index=models.Index(fields=['type', 'envoye'], name='reservationreminder_type__envoye_idx'),
        ),
    ]

