# Generated by Django 5.1.6 on 2026-07-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reservationreminder',
            name='reservationreminder_type__envoye_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_utilisa_d1d2ac_idx',
            old_name='reservation_utilisateur__statut_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_entrepr_8f636a_idx',
            old_name='reservation_entreprise__statut_idx',
        ),
        migrations.RenameIndex(
            model_name='reservationlog',
            new_name='reservation_reserva_80e023_idx',
            old_name='reservationlog_reservation__date_creation_idx',
        ),
        migrations.RenameIndex(
            model_name='reservationparticipant',
            new_name='reservation_reserva_859d88_idx',
            old_name='reservationparticipant_reservation_idx',
        ),
        migrations.RenameIndex(
            model_name='reservationparticipant',
            new_name='reservation_email_b54a53_idx',
            old_name='reservationparticipant_email_idx',
        ),
        migrations.RenameIndex(
            model_name='reservationreminder',
            new_name='reservation_reserva_d25362_idx',
            old_name='reservationreminder_reservation__date_envoi_idx',
        ),
        migrations.RemoveField(
            model_name='reservationreminder',
            name='envoye',
        ),
        migrations.AddField(
            model_name='reservationreminder',
            name='envoyé',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='reservationreminder',
            index=models.Index(fields=['type', 'envoyé'], name='reservation_type_dacdae_idx'),
        ),
    ]
