# Generated by Django 5.1.6 on 2026-07-15 17:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_reservationreminder_reservationreminder_type__envoye_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('ordre', models.PositiveIntegerField(db_index=True, default=0)),
                ('actif', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Méthode de paiement',
                'verbose_name_plural': 'Méthodes de paiement',
            },
        ),
        migrations.AlterField(
            model_name='reservationinvoice',
            name='statut',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('issued', 'Émise'), ('paid', 'Payée'), ('canceled', 'Annulée'), ('refunded', 'Remboursée')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ReservationReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(db_index=True, max_length=80, unique=True)),
                ('pdf', models.FileField(upload_to='reservation/receipts/pdfs/')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('statut', models.CharField(choices=[('draft', 'Brouillon'), ('issued', 'Émis'), ('paid', 'Payé'), ('canceled', 'Annulé'), ('refunded', 'Remboursé')], db_index=True, default='draft', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='reservation.reservationinvoice')),
            ],
            options={
                'verbose_name': 'Reçu',
                'verbose_name_plural': 'Reçus',
            },
        ),
    ]
