# Generated by Django 5.1.6 on 2026-07-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_paymentmethod_alter_reservationinvoice_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('awaiting_payment', 'En attente de paiement'), ('confirmed', 'Confirmée'), ('in_progress', 'En cours'), ('finished', 'Terminée'), ('canceled', 'Annulée'), ('refused', 'Refusée'), ('expired', 'Expirée')], db_index=True, default='draft', max_length=20),
        ),
    ]
