# Generated by Django 6.1 on 2026-08-14 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coworking', '0008_alter_category_id_alter_coworkingspace_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_datetime', models.DateTimeField(db_index=True)),
                ('occupancy_rate_predicted', models.FloatField()),
                ('category_predicted', models.CharField(max_length=20)),
                ('model_version', models.CharField(default='random_forest_v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_logs', to='coworking.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='OccupancySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_type', models.CharField(max_length=30)),
                ('capacity', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('occupancy_count', models.PositiveIntegerField()),
                ('occupancy_rate', models.FloatField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_snapshots', to='coworking.workspace')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['workspace', 'timestamp'], name='forecasting_workspa_e3b563_idx')],
            },
        ),
    ]
